In [44]:
import requests
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

In [45]:
KEY_API_WEATHER = os.environ.get("KEY_API_WEATHER")

In [46]:
response = requests.get(f"https://api.openweathermap.org/data/2.5/weather?q=London&appid={KEY_API_WEATHER}")
data = response.json()
data

{'coord': {'lon': -0.1257, 'lat': 51.5085},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 277.57,
  'feels_like': 277.57,
  'temp_min': 275.4,
  'temp_max': 280.35,
  'pressure': 1042,
  'humidity': 95},
 'visibility': 7000,
 'wind': {'speed': 0.51, 'deg': 270},
 'clouds': {'all': 6},
 'dt': 1641985064,
 'sys': {'type': 2,
  'id': 2019646,
  'country': 'GB',
  'sunrise': 1641974505,
  'sunset': 1642004119},
 'timezone': 0,
 'id': 2643743,
 'name': 'London',
 'cod': 200}

In [47]:
df_coord = pd.read_csv('assets/top_35_coords_final.csv', index_col=0)
df_coord.head()

          lat                 lon
0  48.6359541  -1.511459954959514
1   48.649518          -2.0260409
2  49.2764624          -0.7024738
3  49.4938975           0.1079732
4  49.4404591           1.0939658

In [48]:
cities_coord_lat = []
cities_coord_lon = []
for i, rows in df_coord.iterrows():
    # print(rows)
    cities_coord_lat.append(rows['lat'])
    cities_coord_lon.append(rows['lon'])
display(cities_coord_lat[0:5])
display(cities_coord_lon[0:5])

['48.6359541', '48.649518', '49.2764624', '49.4938975', '49.4404591']

['-1.511459954959514', '-2.0260409', '-0.7024738', '0.1079732', '1.0939658']

In [60]:
lat_1 = cities_coord_lat[0:2]
lon_1 = cities_coord_lon[0:2]
display(lat_1)
display(lon_1)

['48.6359541', '48.649518']

['-1.511459954959514', '-2.0260409']

In [61]:
def get_meteo(lat, lon):
    for data_lat in lat:
        for data_lon in lon:
            response = requests.get(f"https://api.openweathermap.org/data/2.5/weather?lat={data_lat}&lon={data_lon}&appid={KEY_API_WEATHER}")
            data_coords = response.json()
            yield data_coords

In [62]:
get_meteo(lat_1, lon_1)

In [63]:
top_35_temperature = []
for data in get_meteo(lat_1, lon_1):
    print(data['main']['temp'])
    top_35_temperature.append(data['main']['temp'])

281.51
281.67
281.51
281.6

In [64]:
top_35_temperature_final = pd.DataFrame(top_35_temperature)
top_35_temperature_final

        0
0  281.51
1  281.67
2  281.51
3  281.60